trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '03a7fe9e-0691-4b5f-9c69-cb5653bf4bc9'

  # Web app name
  webAppName: 'id-card'

  # Environment name
  environmentName: 'id-card'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x' # Updated to a more recent Node.js version
      displayName: 'Install Node.js'

    - script: |
        cd server
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: 'server' # Adjusted to point to your server directory
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        artifactName: 'drop'
        path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: id-card'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|20.x' # Updated to match the Node.js version used
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start' # Ensure your start script is correctly defined in package.json
